export const USER_LOG_REQUEST = 'USER_LOG_REQUEST'
export const USER_LOG_SUCCESS = 'USER_LOG_SUCCESS'
export const USER_LOG_FAIL = 'USER_LOG_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REG_REQUEST = 'USER_REG_REQUEST'
export const USER_REG_SUCCESS = 'USER_REG_SUCCESS'
export const USER_REG_FAIL = 'USER_REG_FAIL'

